apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-server
  labels:
    app: rest-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rest-server
    spec:
      containers:
        - image: rest-server:v1 #REMOTE_CONTAINER_REGISTRY_TAG
          imagePullPolicy: Never #Always for registry
          name: rest-server
          ports:
            - containerPort: 9090
              protocol: TCP
          env:
            - name: name
              value: "rest-server"
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                    name: cluster-env-config
                    key: APPLICATION_ENVIRONMENT 
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
              httpHeaders:
                - name: Host
                  value: KubernetesLivenessProbe
            initialDelaySeconds: 5
            periodSeconds: 60
