apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-server
  labels:
    app: rest-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rest-server
    spec:
      containers:
        - image: ????????????.dkr.ecr.us-east-1.amazonaws.com/rest-server:latest
          imagePullPolicy: Always
          name: rest-server
          ports:
            - containerPort: 9090
              protocol: TCP
          env:
            - name: name
              value: "rest-server"
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                    name: cluster-env-config
                    key: APPLICATION_ENVIRONMENT 
