apiVersion: v1
kind: Service
metadata:
  name: rest-server
#  tier: backend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  selector:
    app: rest-server-service
#    tier: backend